# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
