# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_restaurant_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address3',
            field=models.CharField(default='NYC', max_length=100),
            preserve_default=False,
        ),
    ]
